# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geral_calc_portfolio_variance_C <- function(phi, q_phi, r_phi, rt, burn_rt, q_rt, r_rt, S, Dt, q_Dt, r_Dt, q_S, r_S, cy2, chisq2) {
    .Call(`_robcdcc_geral_calc_portfolio_variance_C`, phi, q_phi, r_phi, rt, burn_rt, q_rt, r_rt, S, Dt, q_Dt, r_Dt, q_S, r_S, cy2, chisq2)
}

#' @importFrom Rcpp evalCpp
NULL

unconditional_correlation <- function(tilde_epsilon, nobs) {
    .Call(`_robcdcc_unconditional_correlation`, tilde_epsilon, nobs)
}

compositeCDCC_C <- function(alpha, beta, St, nobs, ndim) {
    .Call(`_robcdcc_compositeCDCC_C`, alpha, beta, St, nobs, ndim)
}

calc_Qs_C <- function(phi, rt) {
    .Call(`_robcdcc_calc_Qs_C`, phi, rt)
}

calc_Rt_C <- function(phi, rt, S) {
    .Call(`_robcdcc_calc_Rt_C`, phi, rt, S)
}

loglikelihoodGARCH_C <- function(alpha1, beta1, rt, nobs, h) {
    .Call(`_robcdcc_loglikelihoodGARCH_C`, alpha1, beta1, rt, nobs, h)
}

calc_ht_C <- function(omega, alpha1, beta1, rt, nobs) {
    .Call(`_robcdcc_calc_ht_C`, omega, alpha1, beta1, rt, nobs)
}

corr_reweighted_C <- function(St, chisq2, cy2) {
    .Call(`_robcdcc_corr_reweighted_C`, St, chisq2, cy2)
}

robust_compositeCDCC_C <- function(alpha, beta, St, nobs, ndim, cy1, chisq1, cy2, chisq2) {
    .Call(`_robcdcc_robust_compositeCDCC_C`, alpha, beta, St, nobs, ndim, cy1, chisq1, cy2, chisq2)
}

robust_calc_Qs_C <- function(phi, rt, cy1, chisq1) {
    .Call(`_robcdcc_robust_calc_Qs_C`, phi, rt, cy1, chisq1)
}

robust_calc_Rt_C <- function(phi, rt, S, cy2, chisq2) {
    .Call(`_robcdcc_robust_calc_Rt_C`, phi, rt, S, cy2, chisq2)
}

robust_loglikelihoodGARCH_C <- function(alpha1, beta1, rt, nobs, h, cy, chisq) {
    .Call(`_robcdcc_robust_loglikelihoodGARCH_C`, alpha1, beta1, rt, nobs, h, cy, chisq)
}

robust_calc_ht_C <- function(omega, alpha1, beta1, rt, nobs, cy, chisq) {
    .Call(`_robcdcc_robust_calc_ht_C`, omega, alpha1, beta1, rt, nobs, cy, chisq)
}

#' @importFrom Rcpp evalCpp
NULL

simCDCC_C <- function(phi, S, nobs, seed) {
    .Call(`_robcdcc_simCDCC_C`, phi, S, nobs, seed)
}

