# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geral_calc_portfolio_variance <- function(phi, q_phi, r_phi, rt, burn_rt, cont_rt, S, q_S, r_S, cy2, chisq2) {
    .Call(`_robcdcc_geral_calc_portfolio_variance`, phi, q_phi, r_phi, rt, burn_rt, cont_rt, S, q_S, r_S, cy2, chisq2)
}

real_portfolio_var <- function(phi, S, rt, n) {
    .Call(`_robcdcc_real_portfolio_var`, phi, S, rt, n)
}

#' @importFrom Rcpp evalCpp
NULL

unconditional_correlation <- function(tilde_epsilon, nobs) {
    .Call(`_robcdcc_unconditional_correlation`, tilde_epsilon, nobs)
}

compositeCDCC_C <- function(alpha, beta, epsilon, Dt, nobs, ndim) {
    .Call(`_robcdcc_compositeCDCC_C`, alpha, beta, epsilon, Dt, nobs, ndim)
}

calc_Rt_C <- function(alpha, beta, epsilon, nobs) {
    .Call(`_robcdcc_calc_Rt_C`, alpha, beta, epsilon, nobs)
}

calc_Qs <- function(phi, rt) {
    .Call(`_robcdcc_calc_Qs`, phi, rt)
}

calc_portfolio_variance <- function(phi, hat_phi, rt, cont_rt, S, hat_S) {
    .Call(`_robcdcc_calc_portfolio_variance`, phi, hat_phi, rt, cont_rt, S, hat_S)
}

spearman_corr <- function(St) {
    .Call(`_robcdcc_spearman_corr`, St)
}

corr_reweighted_C <- function(St, chisq2, cy2) {
    .Call(`_robcdcc_corr_reweighted_C`, St, chisq2, cy2)
}

robust_compositeCDCC_C <- function(alpha, beta, St, nobs, ndim, cy1, chisq1, cy2, chisq2) {
    .Call(`_robcdcc_robust_compositeCDCC_C`, alpha, beta, St, nobs, ndim, cy1, chisq1, cy2, chisq2)
}

robust_calc_Qs <- function(phi, rt, cy1, chisq1) {
    .Call(`_robcdcc_robust_calc_Qs`, phi, rt, cy1, chisq1)
}

robust_calc_portfolio_variance <- function(phi, hat_phi, rt, cont_rt, S, hat_S, cy2, chisq2) {
    .Call(`_robcdcc_robust_calc_portfolio_variance`, phi, hat_phi, rt, cont_rt, S, hat_S, cy2, chisq2)
}

#' @importFrom Rcpp evalCpp
NULL

simCDCC_C <- function(phi, S, nobs, seed) {
    .Call(`_robcdcc_simCDCC_C`, phi, S, nobs, seed)
}

